M48
; DRILL file {KiCad 7.0.7} date 2023 November 20, Monday 16:21:26
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-20T16:21:26-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1378
%
G90
G05
T2
X2.2106Y-4.0472
T3
X4.55Y-4.8075
T1
G00X2.0374Y-4.0472
M15
G01X2.0374Y-4.0472
M16
G05
T0
M30
